### ISSUE TITLE
multipart/form-data

### ISSUE THREAD

**Issue by konvulcius** [wildberries-ru/go-transport-generator#25]
//@gtg http-server-content-type multipart/form-data
// @gtg http-server-file-tag any doc
при генерации http-client и http-server происходит конфликт, так как сервер требует *multipart.FileHeader, а клиент требует []*multipart.FileHeader и никак иначе не работает. Можно собрать либо клиент, либо сервер, в паре никак

**Comment by schroding3rscat** [comment]
Already fixed in request #27. You can pass `[]byte` slice instead of `FileHeader`.
